# Generated by Django 4.2.6 on 2023-11-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadona', '0002_promotion_nouveau_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='nouveau_prix',
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
